module.exports = {
  CANT_FIND_SOLDIER: 'عذراً ولكننا لم نستطع إيجاد هذا المجند',
  CANT_FIND_DIVISION: 'عذراً ولكننا لم نستطع إيجاد هذه الوحدة',
  CANT_CHANGE_SAME_UNIT: 'عذراً لا يمكن إعادة توزيع المجند لنفس الوحدة',
  MILITARYID_LENGTH: 'يجب أن يتكون الرقم العسكري من 13 أحرف',
  NATIONALID_LENGTH: 'يجب أن يتكون الرقم العسكري من 13 أحرف',
  MILITARYID_REQUIRED: 'يجب إدخال الرقم العسكرى',
  RECORDID_REQUIRED: 'يجب إدخال رقم السجل',
  NATIONALID_REQUIRED: 'يجب إدخال الرقم القومي',
  TRIPLENUMBER_REQUIRED: 'يجب إدخال الرقم الثلاثي',

  DIVISION_REQUIRED: 'يجب إختيار وحدة المجند',
  JOINDATE_REQUIRED: 'يجب ادخال تاريخ الالتحاق',
  BIRTHDATE_REQUIRED: 'يجب ادخال تاريخ الميلاد',
  FORCE_REQUIRED: 'يجب ادخال سلاح المجند',
  FORCE_INVALID: 'قيمة السلاح خاطئة',
  ARMY_REQUIRED: 'يجب إختيار الجيش/المنطقة',
  ARMY_INVALID: 'قيمة الجيش/المنطقة خاطئة',
  RECRUITMENT_LEVEL_REQUIRED: 'يجب ادخال مرحلة تجنيد المجند',
  RECRUITMENT_LEVEL_INVALID: 'قيمة المرحلة التجنيدية خاطئة',
  EDUCATION_RANK_REQUIRED: 'يجب ادخال مؤهل المجند',
  EDUCATION_RANK_INVALID: 'قيمة المؤهل خاطئة',
  SITUATION_INVALID: 'قيمة الموقف خاظئة',
  RECRUITMENT_AREA_REQUIRED: 'يجب إختيار منطقة التجنيد',
  RECRUITMENT_AREA_INVALID: 'الرجاء التأكد من صحة منطقة التجنيد',
  UNIT_REQUIRED: 'يجب إدخال وحدة المجند',
  NAME_REQUIRED: 'يجب إدخال الإسم',
  GOVERNATE_REQUIRED: 'يجب إختيار المحافظة',
  GOVERNATE_INVALID: 'عذرا ولكن لا نستطيع إيجاد هذه المحافظة تأكد من صحتها',
  CENTRE_REQUIRED: 'يجب إختيار المركز',
  VILLAGE_REQUIRED: 'يجب إدخال القرية',

  MAIL_NUMBER_REQUIRED: 'يجب إدخال رقم المكاتبة',
  MAIL_DATE_REQUIRED: 'يجب إدخال تاريخ المكاتبة',
  MAIL_SENDER_REQUIRED: 'يجب إدخال جهة المكاتبة',
  MAIL_SUBJECT_REQUIRED: 'يجب إدخال موضوع المكاتبة',
  MAIL_RECEIVER_REQUIRED: 'يجب إدخال اسم المستلم',
  MAIL_TYPE_REQUIRED: 'يجب إدخال نوع المكاتبة',
  MAIL_ATTACHMENTS_REQUIRED: 'يجب  إرفاق ملف المكاتبة'
};
